workflows:
  build-apk:
    name: Build APK using EAS
    max_build_duration: 30
    environment:
      vars:
        NODE_ENV: development
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g eas-cli
      - name: EAS Build APK
        script: |
          eas build -p android --profile preview --non-interactive
    artifacts:
      - dist/**/*.apk
    publishing:
      email:
        recipients:
          - aminashukri21@gmail.com
