workflows:
  default-workflow:
    name: Build Blossom Store App
    max_build_duration: 30
    environment:
      vars:
        NODE_ENV: development
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the app
        script: |
          npx expo install
          npx expo prebuild
          npx expo run:android
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - aminashukri21@gmail.com